[build]
  command = "npm run build"
  functions = "functions"
  publish = "_site"
[dev]
  command = "npm run start"
[[plugins]]
  package = "netlify-plugin-inline-functions-env"
  [plugins.inputs]
    include = ["CONTEXT"]
