[build]
  command = "npm run build"
  functions = "functions"
  publish = "_site"
[dev]
  command = "npm run dev"
[[redirects]]
    from = "/api/*"
    to = '/.netlify/functions/:splat'
    status = 200
[[plugins]]
  package = "netlify-plugin-inline-functions-env"
  [plugins.inputs]
    include = ["CONTEXT"]
