[build]
  command = "npm run build"
  functions = "functions"
  publish = "_site"
[dev]
  command = "npm run start"
[[ redirects ]]
    from = "/api/*"
    to = '/.netlify/functions/:splat'
    status = 200
